---
deployment:
  tasks:
    - export DEPLOYPATH=/home/silviame/
    - export PUBLICFOLDERNAME=public_html
    - export BUILDFOLDERNAME=build
    - cd $BUILDFOLDERNAME
    - tar xzf build_v*.tar.gz
    - /bin/rm -rf $DEPLOYPATH/app
    - /bin/rm -rf $DEPLOYPATH/bootstrap
    - /bin/rm -rf $DEPLOYPATH/config
    - /bin/rm -rf $DEPLOYPATH/resources
    - /bin/rm -rf $DEPLOYPATH/routes
    - /bin/rm -rf $DEPLOYPATH/vendor
    - /bin/rm -rf $DEPLOYPATH/storage/app/public/*
    - /bin/rm -rf $DEPLOYPATH/storage/framework/cache/*
    - /bin/rm -rf $DEPLOYPATH/storage/framework/sessions/*
    - /bin/rm -rf $DEPLOYPATH/storage/framework/views/*
    - /bin/rm -rf $DEPLOYPATH/$PUBLICFOLDERNAME/*
    - cd $BUILDFOLDERNAME
    - /bin/cp -R $PUBLICFOLDERNAME $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - cd ..
    - /bin/rm -rf ./$BUILDFOLDERNAME